excludes:
  projects:
  - path: "examples/here-oauth-client-example/pom.xml"
    reason: "EXAMPLE_OF"
    comment: "The project an example how to implement AAA SDK in a client."
  scopes:
  - name: "provided"
    reason: "PROVIDED_BY"
    comment: "These are dependencies provided by the JDK or container at runtime. They are not distributed in the context of this project."
  - name: "test"
    reason: "TEST_TOOL_OF"
    comment: "These are dependencies used for testing. They are not distributed in the context of this project."
