excludes:
  projects:
  - pattern: "*/src/test/**"
    reason: "TEST_OF"
    comment: "Directory is only used for testing."
  - pattern: "examples/here-oauth-client-example/pom.xml"
    reason: "EXAMPLE_OF"
    comment: "The project contains an example how to implement AAA SDK in a client."
  scopes:
  - name: "provided"
    reason: "PROVIDED_DEPENDENCY_OF"
    comment: "Packages provided at runtime by the JDK or container only."
  - name: "test"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
